"""add isactive in spare

Revision ID: 450c04029473
Revises: 6b2260aa807c
Create Date: 2024-12-18 18:14:11.063479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '450c04029473'
down_revision = '6b2260aa807c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_devices')
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('updated_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.drop_index('IDX_spare_parts_model')
        batch_op.drop_index('IDX_spare_parts_serial')
        batch_op.drop_index('IDX_spare_parts_type')
        batch_op.create_foreign_key(None, 'spare_model', ['model_id'], ['model_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('IDX_spare_parts_type', ['spare_type_id'], unique=False)
        batch_op.create_index('IDX_spare_parts_serial', ['serial_number'], unique=False)
        batch_op.create_index('IDX_spare_parts_model', ['model_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True,
               existing_server_default=sa.text('(getdate())'))

    op.create_table('import_devices',
    sa.Column('branch_id', sa.VARCHAR(length=100, collation='Thai_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('teamviewer_id', sa.VARCHAR(length=100, collation='Thai_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('teamviewer_pwd', sa.VARCHAR(length=255, collation='Thai_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('machine_type', sa.VARCHAR(length=100, collation='Thai_CI_AS'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
