"""Add website_url

Revision ID: 48593400fa91
Revises: d197b3d0efdd
Create Date: 2024-12-03 12:10:15.689810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48593400fa91'
down_revision = 'd197b3d0efdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
