"""add remote info to Devices

Revision ID: 4adca8b3d66b
Revises: eb4341077298
Create Date: 2024-11-30 20:05:32.036363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adca8b3d66b'
down_revision = 'eb4341077298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('teamviewer_id', sa.String(length=50), nullable=True),
    sa.Column('teamviewer_pwd', sa.String(length=50), nullable=True),
    sa.Column('anydesk_id', sa.String(length=50), nullable=True),
    sa.Column('anydesk_pwd', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['Branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Devices')
    # ### end Alembic commands ###
