"""add logo field to customer

Revision ID: 4f0cffab17ae
Revises: 76b96c56c6bb
Create Date: 2024-11-29 10:00:47.472334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0cffab17ae'
down_revision = '76b96c56c6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_mimetype', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_column('logo_mimetype')

    # ### end Alembic commands ###
