"""initial migration

Revision ID: 732f43b45876
Revises: 
Create Date: 2024-11-30 17:30:58.592404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732f43b45876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.drop_column('branch_code')

    # ### end Alembic commands ###
