"""add logo field to customer

Revision ID: 76b96c56c6bb
Revises: 81675ff3a303
Create Date: 2024-11-29 08:57:28.795614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b96c56c6bb'
down_revision = '81675ff3a303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('hq_contact_email',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=120),
               existing_nullable=True)
        batch_op.alter_column('hq_address',
               existing_type=sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=500),
               existing_nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.alter_column('hq_address',
               existing_type=sa.Unicode(length=500),
               type_=sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('hq_contact_email',
               existing_type=sa.Unicode(length=120),
               type_=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
