"""add phone field to customer

Revision ID: 81675ff3a303
Revises: 39e731fb32fc
Create Date: 2024-11-28 15:27:15.875811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81675ff3a303'
down_revision = '39e731fb32fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
