"""remove device_type then change to machine_type in devices

Revision ID: 8c786a1835b0
Revises: 0a7063c06398
Create Date: 2024-12-01 12:02:34.066996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c786a1835b0'
down_revision = '0a7063c06398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_column('machine_type')

    # ### end Alembic commands ###
