"""Remove address, contac name, email from branches

Revision ID: b83d3992146d
Revises: ca3b1c1b0321
Create Date: 2024-12-03 09:28:28.223580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83d3992146d'
down_revision = 'ca3b1c1b0321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.NVARCHAR(length=100, collation='Thai_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
