"""Add notes to all model

Revision ID: d197b3d0efdd
Revises: b83d3992146d
Create Date: 2024-12-03 10:03:54.827781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd197b3d0efdd'
down_revision = 'b83d3992146d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
