"""Add customer link and remote

Revision ID: e8818afe8cc3
Revises: 48593400fa91
Create Date: 2024-12-03 14:00:17.605558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8818afe8cc3'
down_revision = '48593400fa91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('hostname')

    # ### end Alembic commands ###
