"""add remote info to Devices

Revision ID: eab55aea15c9
Revises: 4adca8b3d66b
Create Date: 2024-11-30 20:06:14.431774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab55aea15c9'
down_revision = '4adca8b3d66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isactive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Devices', schema=None) as batch_op:
        batch_op.drop_column('isactive')

    # ### end Alembic commands ###
