"""add remote info to branches

Revision ID: eb4341077298
Revises: 732f43b45876
Create Date: 2024-11-30 17:35:43.863784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4341077298'
down_revision = '732f43b45876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teamviewer_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('teamviewer_pwd', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('anydesk_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('anydesk_pwd', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Branches', schema=None) as batch_op:
        batch_op.drop_column('anydesk_pwd')
        batch_op.drop_column('anydesk_id')
        batch_op.drop_column('teamviewer_pwd')
        batch_op.drop_column('teamviewer_id')

    # ### end Alembic commands ###
